In [4]:

import sys
import qiskit
import qiskit_optimization

print("Python path:", sys.executable)
print("Qiskit version:", qiskit.__version__)
print("Qiskit Optimization is working!")

ModuleNotFoundError: No module named 'qiskit_optimization'

In [ ]:
%pip install qiskit-optimization

In [ ]:
import qiskit
import qiskit_optimization

print("Qiskit version:", qiskit.__version__)
print("Qiskit Optimization is working!")

In [6]:

print("Hello Green India!")

import qiskit
print("Qiskit version:", qiskit.__version__)

import qiskit_optimization
print("Qiskit Optimization is working!")

Hello Green India!
Qiskit version: 2.5.2

ModuleNotFoundError: No module named 'qiskit_optimization'

In [7]:

%pip install qiskit-optimization

Collecting qiskit-optimization
  Using cached qiskit_optimization-0.7.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: qiskit<3,>=1.1 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (2.5.2)
Requirement already satisfied: scipy>=1.9.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (1.17.1)
Requirement already satisfied: numpy>=1.17 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (2.4.6)
Collecting docplex!=2.24.231,>=2.21.207 (from qiskit-optimization)
  Using cached docplex-2.32.264-py3-none-any.whl
Requirement already satisfied: setuptools>=40.1.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (84.0.0)
Requirement already satisfied: networkx>=2.6.3 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (3.6.1)
Requirement already satisfied: rustworkx>=0.15.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (0.18.1)
Requirement already satisfied: dill>=0.3 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (0.4.1)
Requirement already satisfied: stevedore>=3.0.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (5.9.1)
Requirement already satisfied: typing-extensions in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (4.16.0)
Requirement already satisfied: six in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from docplex!=2.24.231,>=2.21.207->qiskit-optimization) (1.17.0)
Using cached qiskit_optimization-0.7.0-py3-none-any.whl (237 kB)
Installing collected packages: docplex, qiskit-optimization

   ---------------------------------------- 0/2 [docplex]
   ---------------------------------------- 0/2 [docplex]
   ---------------------------------------- 0/2 [docplex]
   ---------------------------------------- 0/2 [docplex]
   ---------------------------------------- 0/2 [docplex]
   -------------------- ------------------- 1/2 [qiskit-optimization]
   -------------------- ------------------- 1/2 [qiskit-optimization]
   ---------------------------------------- 2/2 [qiskit-optimization]

Successfully installed docplex-2.32.264 qiskit-optimization-0.7.0
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script docplex.exe is installed in 'C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [8]:

import sys
print("Notebook Python:", sys.executable)

%pip show qiskit-optimization

Notebook Python: C:\Users\sravy\miniconda3\envs\qiskit-fallfest\python.exe
Name: qiskit-optimization
Version: 0.7.0
Summary: Qiskit Optimization: A library for optimization applications using quantum computing
Home-page: https://github.com/qiskit-community/qiskit-optimization
Author: Qiskit Optimization Development Team
Author-email: qiskit@us.ibm.com
License: Apache-2.0
Location: C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages
Requires: docplex, networkx, numpy, qiskit, scipy, setuptools
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [9]:

import qiskit_optimization
print("Qiskit Optimization is working!")

Qiskit Optimization is working!

In [10]:

import qiskit_optimization

print("Qiskit Optimization is working!")
print("Ready for Green India quantum optimization.")

Qiskit Optimization is working!
Ready for Green India quantum optimization.

In [11]:

from itertools import product

initiatives = [
    "Tree Plantation",
    "Solar Energy",
    "Waste Management",
    "Pollution Control",
    "Water Conservation"
]

costs = [3, 4, 2, 3, 2]
impacts = [8, 9, 5, 7, 6]
budget = 7

best_score = -1
best_selection = None
best_cost = 0

for selection in product([0, 1], repeat=5):
    total_cost = sum(selection[i] * costs[i] for i in range(5))
    total_score = sum(selection[i] * impacts[i] for i in range(5))

    if total_cost <= budget and total_score > best_score:
        best_score = total_score
        best_selection = selection
        best_cost = total_cost

print("GREEN INDIA - CLASSICAL OPTIMIZATION")
print("Budget:", budget)
print("Selected cost:", best_cost)
print("Estimated impact score:", best_score)
print("\nSelected initiatives:")

for i, selected in enumerate(best_selection):
    if selected:
        print("-", initiatives[i])

GREEN INDIA - CLASSICAL OPTIMIZATION
Budget: 7
Selected cost: 7
Estimated impact score: 19

Selected initiatives:
- Tree Plantation
- Waste Management
- Water Conservation

In [12]:
%pip install qiskit-optimization qiskit-algorithms

Requirement already satisfied: qiskit-optimization in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (0.7.0)
Collecting qiskit-algorithms
  Downloading qiskit_algorithms-0.4.0-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: qiskit<3,>=1.1 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (2.5.2)
Requirement already satisfied: scipy>=1.9.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (1.17.1)
Requirement already satisfied: numpy>=1.17 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (2.4.6)
Requirement already satisfied: docplex!=2.24.231,>=2.21.207 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (2.32.264)
Requirement already satisfied: setuptools>=40.1.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (84.0.0)
Requirement already satisfied: networkx>=2.6.3 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit-optimization) (3.6.1)
Requirement already satisfied: rustworkx>=0.15.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (0.18.1)
Requirement already satisfied: dill>=0.3 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (0.4.1)
Requirement already satisfied: stevedore>=3.0.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (5.9.1)
Requirement already satisfied: typing-extensions in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from qiskit<3,>=1.1->qiskit-optimization) (4.16.0)
Requirement already satisfied: six in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from docplex!=2.24.231,>=2.21.207->qiskit-optimization) (1.17.0)
Downloading qiskit_algorithms-0.4.0-py3-none-any.whl (327 kB)
Installing collected packages: qiskit-algorithms
Successfully installed qiskit-algorithms-0.4.0
Note: you may need to restart the kernel to use updated packages.

In [13]:

from qiskit_optimization import QuadraticProgram

# Create the optimization problem
problem = QuadraticProgram("Green_India_Optimization")

initiatives = [
    "Tree_Plantation",
    "Solar_Energy",
    "Waste_Management",
    "Pollution_Control",
    "Water_Conservation"
]

costs = [3, 4, 2, 3, 2]
impacts = [8, 9, 5, 7, 6]
budget = 7

# Binary decision variables:
# 1 = select initiative, 0 = do not select
for name in initiatives:
    problem.binary_var(name=name)

# Maximize the estimated impact score
problem.maximize(
    linear=dict(zip(initiatives, impacts))
)

# Keep total cost within the budget
problem.linear_constraint(
    linear=dict(zip(initiatives, costs)),
    sense="<=",
    rhs=budget,
    name="Budget_Constraint"
)

print(problem.prettyprint())

Problem name: Green_India_Optimization

Maximize
  7*Pollution_Control + 9*Solar_Energy + 8*Tree_Plantation + 5*Waste_Management
  + 6*Water_Conservation

Subject to
  Linear constraints (1)
    3*Pollution_Control + 4*Solar_Energy + 3*Tree_Plantation
    + 2*Waste_Management + 2*Water_Conservation <= 7  'Budget_Constraint'

  Binary variables (5)
    Tree_Plantation Solar_Energy Waste_Management Pollution_Control
    Water_Conservation

In [14]:

from qiskit.primitives import StatevectorSampler
from qiskit_optimization.minimum_eigensolvers import QAOA
from qiskit_optimization.algorithms import MinimumEigenOptimizer
from qiskit_optimization.optimizers import COBYLA

# Create the QAOA algorithm
sampler = StatevectorSampler(seed=42)

qaoa = QAOA(
    sampler=sampler,
    optimizer=COBYLA(maxiter=100),
    reps=1
)

# Connect QAOA to the optimization problem
quantum_optimizer = MinimumEigenOptimizer(qaoa)

print("Starting Green India QAOA optimization...")

# Run the optimization
qaoa_result = quantum_optimizer.solve(problem)

print("\nQAOA RESULT")
print("-----------")
print(qaoa_result.prettyprint())

Starting Green India QAOA optimization...

QAOA RESULT
-----------
objective function value: 19.0
variable values: Tree_Plantation=1.0, Solar_Energy=0.0, Waste_Management=1.0, Pollution_Control=0.0, Water_Conservation=1.0
status: SUCCESS

In [15]:

import pandas as pd

# Extract the actual QAOA solution
solution_values = qaoa_result.x

initiative_names = [
    "Tree Plantation",
    "Solar Energy",
    "Waste Management",
    "Pollution Control",
    "Water Conservation"
]

costs = [3, 4, 2, 3, 2]
impacts = [8, 9, 5, 7, 6]
budget = 7

# Convert solution values into binary decisions
selected_values = [
    int(round(value)) for value in solution_values
]

# Calculate actual result metrics
quantum_cost = sum(
    selected_values[i] * costs[i]
    for i in range(len(initiative_names))
)

quantum_score = sum(
    selected_values[i] * impacts[i]
    for i in range(len(initiative_names))
)

print("GREEN INDIA - QAOA RESULT")
print("-------------------------")
print("Selected cost:", quantum_cost)
print("Estimated impact score:", quantum_score)
print("Budget:", budget)
print("Budget feasible:", quantum_cost <= budget)

print("\nSelected initiatives:")
for i, selected in enumerate(selected_values):
    if selected:
        print("-", initiative_names[i])

# Create a detailed table of the actual QAOA result
quantum_details = pd.DataFrame({
    "Initiative": initiative_names,
    "Cost": costs,
    "Estimated Impact Score": impacts,
    "Selected": selected_values
})

display(quantum_details)

ModuleNotFoundError: No module named 'pandas'

In [16]:

%pip install pandas

Collecting pandas
  Using cached pandas-3.0.6-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.5-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in C:\Users\sravy\miniconda3\envs\qiskit-fallfest\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.6-cp311-cp311-win_amd64.whl (9.9 MB)
Using cached tzdata-2026.5-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.6 tzdata-2026.5
Note: you may need to restart the kernel to use updated packages.

In [17]:

import pandas as pd

print("Pandas version:", pd.__version__)
print("Pandas is working!")

Pandas version: 3.0.6
Pandas is working!

In [18]:
import pandas as pd

print("Pandas version:", pd.__version__)
print("Pandas is working successfully!")

Pandas version: 3.0.6
Pandas is working successfully!

In [19]:

import pandas as pd
from itertools import product

# Green India project data (illustrative values)
initiatives = [
    "Tree Plantation",
    "Solar Energy",
    "Waste Management",
    "Pollution Control",
    "Water Conservation"
]

costs = [3, 4, 2, 3, 2]
impacts = [8, 9, 5, 7, 6]
budget = 7

# Find the best classical solution
best_score = -1
best_selection = []

for selection in product([0, 1], repeat=len(initiatives)):
    total_cost = sum(
        selection[i] * costs[i] for i in range(len(initiatives))
    )
    total_score = sum(
        selection[i] * impacts[i] for i in range(len(initiatives))
    )

    if total_cost <= budget and total_score > best_score:
        best_score = total_score
        best_selection = list(selection)

classical_cost = sum(
    best_selection[i] * costs[i] for i in range(len(initiatives))
)

# Read the QAOA result from your previous cell
quantum_selection = [int(round(x)) for x in qaoa_result.x]

quantum_cost = sum(
    quantum_selection[i] * costs[i] for i in range(len(initiatives))
)
quantum_score = sum(
    quantum_selection[i] * impacts[i] for i in range(len(initiatives))
)

# Display comparison
comparison = pd.DataFrame({
    "Method": ["Classical Optimization", "Quantum QAOA"],
    "Total Cost": [classical_cost, quantum_cost],
    "Estimated Impact Score": [best_score, quantum_score],
    "Within Budget": [
        classical_cost <= budget,
        quantum_cost <= budget
    ]
})

print("GREEN INDIA: CLASSICAL VS QUANTUM")
print("Budget:", budget)
display(comparison)

print("\nClassical selected initiatives:")
for i, selected in enumerate(best_selection):
    if selected:
        print("-", initiatives[i])

print("\nQuantum QAOA selected initiatives:")
for i, selected in enumerate(quantum_selection):
    if selected:
        print("-", initiatives[i])

GREEN INDIA: CLASSICAL VS QUANTUM
Budget: 7

                   Method  Total Cost  Estimated Impact Score  Within Budget
0  Classical Optimization           7                      19           True
1            Quantum QAOA           7                      19           True

Classical selected initiatives:
- Tree Plantation
- Waste Management
- Water Conservation

Quantum QAOA selected initiatives:
- Tree Plantation
- Waste Management
- Water Conservation

In [20]:

comparison.to_csv("green_india_final_comparison.csv", index=False)
print("Comparison saved successfully!")

Comparison saved successfully!

In [21]:

from pathlib import Path

project_folder = Path(
    r"C:\Users\sravy\OneDrive\Desktop\GreenIndia"
)

project_folder.mkdir(parents=True, exist_ok=True)

csv_path = project_folder / "green_india_final_comparison.csv"

comparison.to_csv(csv_path, index=False)

print("Comparison file saved at:")
print(csv_path)
print("\nSaved comparison:")
display(comparison)

Comparison file saved at:
C:\Users\sravy\OneDrive\Desktop\GreenIndia\green_india_final_comparison.csv

Saved comparison:

                   Method  Total Cost  Estimated Impact Score  Within Budget
0  Classical Optimization           7                      19           True
1            Quantum QAOA           7                      19           True

In [22]:
python -m pip install streamlit pandas

SyntaxError: invalid syntax (2483787530.py, line 1)